### ISSUE TITLE
Emit INLINE and INLINE_ORIGIN directives

### ISSUE THREAD

**Issue by gabrielesvelto** [mozilla/dump_syms#280]
Breakpad added support for inlined functions in revision [4f5b8147](https://chromium.googlesource.com/breakpad/breakpad/+/4f5b814790301e7b8252535e0732bee11f4bb801), we should support it too. Note that in breakpad's dump_syms INLINE and INLINE_ORIGIN directives are emitted conditionally because they increase the size of the output significantly (they use the [-d](https://chromium.googlesource.com/breakpad/breakpad/+/refs/heads/main/src/tools/linux/dump_syms/dump_syms.cc#80) flag for it).

**Comment by mstange** [comment]
If I wanted to implement this today, what would be the blockers? Which downstream consumers of .sym files exist and which of them would we need to make compatible with the new format first (e.g. by ignoring the new lines)?

**Comment by mstange** [comment]
This is the list:

 - The current stackwalker, https://github.com/mozilla-services/minidump-stackwalk/issues/49
 - Tecken, https://bugzilla.mozilla.org/show_bug.cgi?id=1731368
 - Eliot, https://bugzilla.mozilla.org/show_bug.cgi?id=1731367

Once these workarounds are in place, this issue will be unblocked.

To actually make use of the data, we have https://github.com/getsentry/symbolic/issues/432 and https://github.com/luser/rust-minidump/issues/239.

**Comment by willkg** [comment]
The Tecken bug (1731368) is straight-forward: ignore all the INLINE lines.

The other two are more complicated because we effectively have to convert from the sym-with-inlines to sym-without-inlines format to maintain the "we've got the line at the outermost level" thing.

I can fix Eliot, but probably won't get to it until after I've got it in prod.

I don't think I can fix the current stackwalker any time soon. I'm hoping that we can switch to rust-minidump and then not do it. But that means we'd have to implement ignoring INLINE lines in rust-minidump until it's supported in symbolic.

**Comment by gabrielesvelto** [comment]
If we implement support here behind a flag like Google did we can start testing it without having to immediately introduce the functionality in our crash reporting pipeline.

**Comment by willkg** [comment]
We can't use this in production until we know that all the downstream users of sym files can handle these lines.

**Comment by willkg** [comment]
That works for me! I just panicked because you said "I've started working on this." and I had no idea what that entailed I know I've got downstream stuff that will die and I can't get to fixing it any time soon.
